### ISSUE TITLE
UltraPro wfd4001 light switch works with ESPHome even though this tool says it doesn't.

### ISSUE THREAD

**Issue by eyal0** [libretuya/upk2esphome#20]
I purchased this device: https://a.co/d/0u4K7UM

I think that it the the same one as this: https://upk.libretiny.eu/?profile=ultrapro-wfd4001-light-switch-v1.1.14

The `image_url` matches the one that I bought and the brand name and version number match also.

I put ESPHome on it this morning and it's work great.  I was able to program it so that pressing on the paddles correctly toggles the LED and the lights.  Also, I can use the Home Assistant app with ESPHome to turn my lights on and off.

Is the website wrong about this device?

This is a working yaml config: 

```
esphome:
  name: ultrapro-light-switch
  friendly_name: UltraPro Light Switch

bk72xx:
  board: wb3s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
captive_portal:

# Identifying all the pins.
output:
  - platform: libretiny_pwm
    id: output_blue_led
    pin: PWM4
switch:
  - platform: gpio
    pin: PWM5
    id: relay
    name: Relay
    restore_mode: RESTORE_DEFAULT_OFF
    device_class: switch
binary_sensor:
  - platform: gpio
    pin:
      number: PWM2
      inverted: True
    id: input_on_button
    on_press: 
      then:
        - light.turn_on: blue_led
        - switch.turn_on: relay
  - platform: gpio
    pin: 
      number: PWM3
      inverted: True
    id: input_off_button
    on_press:
      then:
        - light.turn_off: blue_led
        - switch.turn_off: relay
light:
  - platform: status_led
    id: blue_led
    name: Blue LED
    output: output_blue_led
    disabled_by_default: True
    restore_mode: RESTORE_DEFAULT_OFF
```
